title: Jingyi (Sally) Xu
position: PhD candidate
affiliation: Shanghai Jiao Tong University
email: jingyi.xu@sjtu.edu.cn / xjy981212@163.com
keywords: minimal academic
google_scholar: https://scholar.google.com.hk/citations?hl=zh-CN&user=f6Zn-9gAAAAJ
github_link: https://github.com/BIT-XJY
avatar: ./assets/img/Sally.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
